name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Clean and Build
        run: |
          cd GamelandShop.Web/GamelandShop.Web.Client
          dotnet clean
          dotnet publish -c Release -o bin/publish

      - name: Debug - List build output
        run: |
          echo "=== ZAWARTOŚĆ PUBLISH FOLDERU ==="
          ls -la GamelandShop.Web/GamelandShop.Web.Client/bin/Release/net9.0/publish/wwwroot/
          echo "=== CZY INDEX.HTML ISTNIEJE? ==="
          find . -name "index.html" -type f | head -5
          echo "=== CZY BLAZOR.WEBASSEMBLY.JS ISTNIEJE? ==="
          find . -name "blazor.webassembly.js" -type f | head -5
          echo "=== STRUKTURA FRAMEWORK ==="
          ls -la GamelandShop.Web/GamelandShop.Web.Client/bin/Release/net9.0/publish/wwwroot/_framework/ | head -10

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "GamelandShop.Web/GamelandShop.Web.Client"
          output_location: "bin/Release/net9.0/publish/wwwroot"
          app_build_command: "dotnet publish -c Release -o bin/publish"
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
